config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show, :index]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true

  include Commentable
  end

app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable
  end

  def receive_comment(content)
    self.comments.find_or_create_by(content: content)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :content, :author_id, presence: true

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  has_many :post_subs, dependent: :destroy, inverse_of: :post

  has_many :subs,
    through: :post_subs,
    source: :sub
end

app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  validates :post, :sub, presence: true
  validates :post_id, uniqueness: { scope: :sub_id }

  belongs_to :post

  belongs_to :sub

end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :description, :moderator_id, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :post_subs, dependent: :destroy, inverse_of: :sub

  has_many :posts,
    through: :post_subs,
    source: :post
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 8, allow_nil: true }

  has_many :subs,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :Sub

  has_many :posts, dependent: :destroy,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :Post

  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user
    return user if user.is_password?(password)
    nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(32)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    password_object = BCrypt::Password.new(self.password_digest)
    password_object.is_password?(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login(user)
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      render :new
    end
  end

  def new
    @post = Post.new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub)
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
    if @post
      render :edit
    else
      redirect_to new_post_url
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      render :edit
    end
  end

  def index
    redirect_to subs_url
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :author_id, sub_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(session_params[:username], session_params[:password])

    if @user
      login(@user)
      redirect_to users_url
    else
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_user_url
  end

  private

  def session_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :is_moderator?, only: [:edit, :destroy]
  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def edit
    @sub = Sub.find(params[:id])
    if @sub
      render :edit
    else
      flash[:errors] << "Can't edit sub that does not exist"
      redirect_to new_sub_url
    end
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      render :edit
    end
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    redirect_to subs_url
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)
  end

  def is_moderator?
    @sub = Sub.find(params[:id])
    redirect_to sub_url(@sub) if current_user.nil? || current_user.id != @sub.moderator_id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input name='authenticity_token' type='hidden' value='#{form_authenticity_token}'>".html_safe
  end

  def delete_button(path)
    link_to "Delete", path, method: :delete
  end

  def edit_button(path)
    link_to "Edit", path, method: :get
  end

  def create_button(path)
    button_to "Create", path, method: :get
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login_button
    button_to "Log In", new_session_url, method: :get
  end

  def logout_button
    button_to "Log Out", session_url, method: :delete
    ## remember dis ##
  end

  # def create_button
  #   button_to "Create", new_sub_url, method: :get
  # end
end

app/helpers/subs_helper.rb
module SubsHelper
  # def delete_button(sub)
  #   link_to "Delete", sub_url(sub), method: :delete
  # end
  #
  # def edit_button(sub)
  #   link_to "Edit", edit_sub_url(sub), method: :get
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
    <%= logout_button %>
  <% else %>
    <%= login_button %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<% action = post.persisted? ? post_url(post) : posts_url %>
<% method = post.persisted? ? "PATCH" : "POST" %>

<form action="<%= action %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="title">Title</label>
  <input type="text" name="post[title]" id="title" value="<%= post.title %>">
  <br>

  <label>Content</label>
  <br>
  <textarea name="post[content]" rows="8" cols="40"><%= post.content %></textarea>
  <br>

  <label for="sub_id">Sub</label>

  <input type="hidden" name="post[sub_ids][]" value="">

  <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input type="checkbox"
        value="<%= sub.id %>"
        name="post[sub_ids][]"
        <%= 'checked' if post.sub_ids.include?(sub.id) %>>
    </label>
  <% end %>
  <br>

  <label for="author_id">Author</label>
  <select name="post[author_id]">
  <% User.all.each do |user| %>
    <option value="<%= user.id %>" <%= 'selected' if user.id == post.author_id %>><%= user.username %></option>
  <% end %>
  </select>
  <br>

  <% button_text = post.persisted? ? "Save" : "Create" %>
  <input type="submit" value="<%= button_text %>">
</form>

app/views/posts/edit.html.erb
<h2>Edit a Post</h2>
<%= render "form", post: @post %>

app/views/posts/new.html.erb
<h2>Create a Post</h2>
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<h3><%= @post.author.username %></h3>
<h5><%= localize(@post.created_at, format: :long) %></h5>

<label>Related Subs</label>
<ul>
  <% @post.subs.each do |sub|  %>
    <li><%= link_to sub.title, sub_url(sub), method: :get %></li>
  <% end %>
</ul>

<h3>Post Content</h3>
<section>
  <%= @post.content %>
    <%= edit_button(edit_post_url(@post)) %> <%= delete_button(post_url(@post)) %>
</section>

app/views/shared/_errors.html.erb
<ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>

app/views/subs/_form.html.erb
<% method = sub.persisted? ? "PATCH" : "POST" %>
<% action = sub.persisted? ? sub_url(sub) : subs_url %>
<form action="<%= action %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= method %>">
  <label for="title">Title</label>
  <input type="text" id="title" name="sub[title]" value="<%= sub.title %>">
  <br>
  <label>Description</label>
  <br>
  <textarea name="sub[description]" rows="8" cols="40"><%= sub.description %></textarea>
  <br>
  <select name="sub[moderator_id]">
    <% User.all.each do |user| %>
      <option value="<%= user.id %>" <%= 'selected' if sub.moderator_id == user.id %>>
        <%= user.username %>
      </option>
    <% end %>
  </select>
  <br>
  <% button_text = sub.persisted? ? "Save" : "Create" %>
  <input type="submit" value="<%= button_text %>">
</form>

app/views/subs/edit.html.erb
<h1>Edit a sub</h1>
<%= render "form", sub: @sub %>

app/views/subs/index.html.erb
<h1>Subs</h1>
  <ul>
  <% @subs.each do |sub| %>
    <li><%= link_to sub.title, sub_url(sub), method: :get %> <%= edit_button(edit_sub_url(sub)) %> <%= delete_button(sub_url(sub)) %></li>
  <% end %>

  </ul>
  <%= create_button(new_sub_url) %>

app/views/subs/new.html.erb
<h1>Create a sub</h1>
<%= render "form", sub: @sub %>

app/views/subs/show.html.erb
<h2><%= @sub.title %></h2>
<section>
  <%= @sub.description %>
  <%= edit_button(edit_sub_url(@sub)) %> <%= delete_button(sub_url(@sub)) %>
</section>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
<% @users.each do |user| %>
  <li><%= user.username %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%= users_url %>" method="post">
  <%= auth_token %>
  <label for="username">Username</label>
  <input type="text" id="username" name="user[username]">
  <br>
  <label for="password">Password</label>
  <input type="password" id="password" name="user[password]">
  <br>
  <input type="submit" value="Create user">
</form>

app/views/users/show.html.erb
<h1>Hi <%= @user.username %></h1>